version: '3'

services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - 5432:5432
    networks:
      - DS
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  superset:
    image: apache/superset:latest
    container_name: apache_superset
    ports:
      - "8089:8088"
    environment:
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://superset:superset@postgres:5432/superset
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - DS

networks:
  DS:
    external: true
