# Generated by Django 4.1 on 2024-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="created_at",
        ),
    ]
