# Generated by Django 4.1 on 2024-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_laptop_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="card",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="card_brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="cpu",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="cpu_brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="hard_drive_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="hard_drive_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="new",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="old",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="ram_brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="ram_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="screen_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="screen_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
