# Generated by Django 4.1 on 2024-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_laptop_brand_alter_laptop_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="screen_size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
